package faang.school.postservice.protobuf.generate;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: comment_published_event.proto
// Protobuf Java Version: 4.28.3

public final class CommentPublishedEventProto {
  private CommentPublishedEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      CommentPublishedEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentPublishedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommentPublishedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 authorId = 3;</code>
     * @return The authorId.
     */
    long getAuthorId();

    /**
     * <code>int64 postId = 4;</code>
     * @return The postId.
     */
    long getPostId();

    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
  }
  /**
   * Protobuf type {@code CommentPublishedEvent}
   */
  public static final class CommentPublishedEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CommentPublishedEvent)
      CommentPublishedEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        CommentPublishedEvent.class.getName());
    }
    // Use CommentPublishedEvent.newBuilder() to construct.
    private CommentPublishedEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CommentPublishedEvent() {
      content_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommentPublishedEventProto.internal_static_CommentPublishedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommentPublishedEventProto.internal_static_CommentPublishedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommentPublishedEventProto.CommentPublishedEvent.class, CommentPublishedEventProto.CommentPublishedEvent.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORID_FIELD_NUMBER = 3;
    private long authorId_ = 0L;
    /**
     * <code>int64 authorId = 3;</code>
     * @return The authorId.
     */
    @java.lang.Override
    public long getAuthorId() {
      return authorId_;
    }

    public static final int POSTID_FIELD_NUMBER = 4;
    private long postId_ = 0L;
    /**
     * <code>int64 postId = 4;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, content_);
      }
      if (authorId_ != 0L) {
        output.writeInt64(3, authorId_);
      }
      if (postId_ != 0L) {
        output.writeInt64(4, postId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getDate());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, content_);
      }
      if (authorId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, authorId_);
      }
      if (postId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, postId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommentPublishedEventProto.CommentPublishedEvent)) {
        return super.equals(obj);
      }
      CommentPublishedEventProto.CommentPublishedEvent other = (CommentPublishedEventProto.CommentPublishedEvent) obj;

      if (getId()
          != other.getId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getAuthorId()
          != other.getAuthorId()) return false;
      if (getPostId()
          != other.getPostId()) return false;
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + AUTHORID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuthorId());
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostId());
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CommentPublishedEventProto.CommentPublishedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CommentPublishedEventProto.CommentPublishedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CommentPublishedEventProto.CommentPublishedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommentPublishedEventProto.CommentPublishedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommentPublishedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommentPublishedEvent)
        CommentPublishedEventProto.CommentPublishedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommentPublishedEventProto.internal_static_CommentPublishedEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommentPublishedEventProto.internal_static_CommentPublishedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommentPublishedEventProto.CommentPublishedEvent.class, CommentPublishedEventProto.CommentPublishedEvent.Builder.class);
      }

      // Construct using CommentPublishedEventProto.CommentPublishedEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        content_ = "";
        authorId_ = 0L;
        postId_ = 0L;
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommentPublishedEventProto.internal_static_CommentPublishedEvent_descriptor;
      }

      @java.lang.Override
      public CommentPublishedEventProto.CommentPublishedEvent getDefaultInstanceForType() {
        return CommentPublishedEventProto.CommentPublishedEvent.getDefaultInstance();
      }

      @java.lang.Override
      public CommentPublishedEventProto.CommentPublishedEvent build() {
        CommentPublishedEventProto.CommentPublishedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CommentPublishedEventProto.CommentPublishedEvent buildPartial() {
        CommentPublishedEventProto.CommentPublishedEvent result = new CommentPublishedEventProto.CommentPublishedEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CommentPublishedEventProto.CommentPublishedEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.authorId_ = authorId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.postId_ = postId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.date_ = dateBuilder_ == null
              ? date_
              : dateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommentPublishedEventProto.CommentPublishedEvent) {
          return mergeFrom((CommentPublishedEventProto.CommentPublishedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommentPublishedEventProto.CommentPublishedEvent other) {
        if (other == CommentPublishedEventProto.CommentPublishedEvent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAuthorId() != 0L) {
          setAuthorId(other.getAuthorId());
        }
        if (other.getPostId() != 0L) {
          setPostId(other.getPostId());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                authorId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                postId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                input.readMessage(
                    getDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long authorId_ ;
      /**
       * <code>int64 authorId = 3;</code>
       * @return The authorId.
       */
      @java.lang.Override
      public long getAuthorId() {
        return authorId_;
      }
      /**
       * <code>int64 authorId = 3;</code>
       * @param value The authorId to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorId(long value) {

        authorId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 authorId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        authorId_ = 0L;
        onChanged();
        return this;
      }

      private long postId_ ;
      /**
       * <code>int64 postId = 4;</code>
       * @return The postId.
       */
      @java.lang.Override
      public long getPostId() {
        return postId_;
      }
      /**
       * <code>int64 postId = 4;</code>
       * @param value The postId to set.
       * @return This builder for chaining.
       */
      public Builder setPostId(long value) {

        postId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 postId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        postId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
        } else {
          dateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            date_ != null &&
            date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getDateBuilder().mergeFrom(value);
          } else {
            date_ = value;
          }
        } else {
          dateBuilder_.mergeFrom(value);
        }
        if (date_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        date_ = null;
        if (dateBuilder_ != null) {
          dateBuilder_.dispose();
          dateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp date = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CommentPublishedEvent)
    }

    // @@protoc_insertion_point(class_scope:CommentPublishedEvent)
    private static final CommentPublishedEventProto.CommentPublishedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommentPublishedEventProto.CommentPublishedEvent();
    }

    public static CommentPublishedEventProto.CommentPublishedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommentPublishedEvent>
        PARSER = new com.google.protobuf.AbstractParser<CommentPublishedEvent>() {
      @java.lang.Override
      public CommentPublishedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommentPublishedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommentPublishedEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CommentPublishedEventProto.CommentPublishedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentPublishedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommentPublishedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035comment_published_event.proto\032\037google/" +
      "protobuf/timestamp.proto\"\200\001\n\025CommentPubl" +
      "ishedEvent\022\n\n\002id\030\001 \001(\003\022\017\n\007content\030\002 \001(\t\022" +
      "\020\n\010authorId\030\003 \001(\003\022\016\n\006postId\030\004 \001(\003\022(\n\004dat" +
      "e\030\005 \001(\0132\032.google.protobuf.TimestampB\034B\032C" +
      "ommentPublishedEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_CommentPublishedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommentPublishedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CommentPublishedEvent_descriptor,
        new java.lang.String[] { "Id", "Content", "AuthorId", "PostId", "Date", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
