// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: like_post_event.proto
// Protobuf Java Version: 4.28.3

package faang.school.postservice.protobuf.generate;

public final class LikePostEventProto {
  private LikePostEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      LikePostEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LikePostEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LikePostEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 postId = 2;</code>
     * @return The postId.
     */
    long getPostId();

    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code LikePostEvent}
   */
  public static final class LikePostEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LikePostEvent)
      LikePostEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        LikePostEvent.class.getName());
    }
    // Use LikePostEvent.newBuilder() to construct.
    private LikePostEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LikePostEvent() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return faang.school.postservice.protobuf.generate.LikePostEventProto.internal_static_LikePostEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return faang.school.postservice.protobuf.generate.LikePostEventProto.internal_static_LikePostEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.class, faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int POSTID_FIELD_NUMBER = 2;
    private long postId_ = 0L;
    /**
     * <code>int64 postId = 2;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (postId_ != 0L) {
        output.writeInt64(2, postId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (postId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, postId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent)) {
        return super.equals(obj);
      }
      faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent other = (faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent) obj;

      if (getId()
          != other.getId()) return false;
      if (getPostId()
          != other.getPostId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LikePostEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LikePostEvent)
        faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return faang.school.postservice.protobuf.generate.LikePostEventProto.internal_static_LikePostEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return faang.school.postservice.protobuf.generate.LikePostEventProto.internal_static_LikePostEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.class, faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.Builder.class);
      }

      // Construct using faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        postId_ = 0L;
        userId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return faang.school.postservice.protobuf.generate.LikePostEventProto.internal_static_LikePostEvent_descriptor;
      }

      @java.lang.Override
      public faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent getDefaultInstanceForType() {
        return faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.getDefaultInstance();
      }

      @java.lang.Override
      public faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent build() {
        faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent buildPartial() {
        faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent result = new faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.postId_ = postId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userId_ = userId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent) {
          return mergeFrom((faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent other) {
        if (other == faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getPostId() != 0L) {
          setPostId(other.getPostId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                postId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long postId_ ;
      /**
       * <code>int64 postId = 2;</code>
       * @return The postId.
       */
      @java.lang.Override
      public long getPostId() {
        return postId_;
      }
      /**
       * <code>int64 postId = 2;</code>
       * @param value The postId to set.
       * @return This builder for chaining.
       */
      public Builder setPostId(long value) {

        postId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 postId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        postId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LikePostEvent)
    }

    // @@protoc_insertion_point(class_scope:LikePostEvent)
    private static final faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent();
    }

    public static faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LikePostEvent>
        PARSER = new com.google.protobuf.AbstractParser<LikePostEvent>() {
      @java.lang.Override
      public LikePostEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LikePostEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LikePostEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public faang.school.postservice.protobuf.generate.LikePostEventProto.LikePostEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LikePostEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LikePostEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025like_post_event.proto\";\n\rLikePostEvent" +
      "\022\n\n\002id\030\001 \001(\003\022\016\n\006postId\030\002 \001(\003\022\016\n\006userId\030\003" +
      " \001(\003B@\n*faang.school.postservice.protobu" +
      "f.generateB\022LikePostEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LikePostEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LikePostEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LikePostEvent_descriptor,
        new java.lang.String[] { "Id", "PostId", "UserId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
