DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS album CASCADE;
DROP TABLE IF EXISTS post_album CASCADE;
DROP TABLE IF EXISTS favorite_albums CASCADE;
