DROP TABLE post_album;
DROP TABLE likes;
DROP TABLE comment;
DROP TABLE post;
DROP TABLE favorite_albums;
DROP INDEX album_author_title_idx;
DROP TABLE album;
DROP TABLE post_resource;
DROP TABLE users_with_access;