spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post-service
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
  cloud:
    openfeign:
      client:
        config:
            default:
                connectTimeout: 5_000
                readTimeout: 10_000

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 5s
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
  circuitbreaker:
    instances:
      default:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException


server:
  port: 8081
  servlet:
    context-path: /posts/api

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info

post:
  moderation:
    batch-size: 10
    page-size: 20
    cronPeriod: "0 0 0 * * *"
  schedule:
    batch-size: 1000
    scheduled-cron: "0 * * * * *"
    max-retries: 5
    timeout: 10
    initial-delay: 500
    delay-multiplier: 2
    batchCount: 3
  grammar:
    cronPeriod: "0 0 0 * * *"
    batch-size: 20
    page-size: 20

thread:
  pool:
    size: 10

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: postbucket
    max_image_size: 5
  grammar:
    key: ${GRAMMAR_KEY}


user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: debug
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: info