spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
          calculations_channel_name: cal
          user_ban_name: user_ban
          like_event_name: like_event
    kafka:
      bootstrap-servers: localhost:9092, localhost:9192, localhost:9292
      group_id: event-listeners
      auto_offset: earliest
      concurrency: 3

    cache:
      type: redis
      redis:
        cache-null-values: false

  task:
    execution:
      pool:
        size: 10
        max-size: 10

server:
  port: 8081

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: projectbucket
    isMocked: false
  user-service:
    host: localhost
    port: 8080
  project-service:
    host: localhost
    port: 8082
  payment-service:
    host: localhost
    port: 9080
scheduler:
  expired-ad:
    batch-size: 100
    cron: 0 0 0 * * ?

executor-service:
  threads-count: 2
  termination-timeout: 30

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api-docs


project:
    ban-user:
      cron: 0 0 1 * * *
    post-publisher:
      cron: "0 * * * * *"

thread:
  pool:
    coreSize: 5
    maxSize: 10
    prefix: "post-publisher-"

entity:
    post:
        max-unverified-count-for-ban: 5
    commentServiceFileLimitMb: 5
languagetool:
  apiUrl: "https://api.languagetool.org/v2/check"
  language: "auto"

retry:
  text-auto-correction-api:
    max-attempts: 3
    backoff:
      delay: 2000
      multiplier: 1.5

cache:
  config:
    default-ttl: 10m
    authors-ttl: 24h
