spring:
  mvc:
    servlet:
      path:
        '/api/v1'

      multipart:
        enabled: true
        max-file-size: 5MB
        max-request-size: 5MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:9092
      security:
        protocol: PLAINTEXT
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 1000
      properties:
        linger-ms: 30000
        spring.json.add.type.headers: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

springdoc:
  packages-to-scan: faang.school.postservice.controller

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

resource:
  limit: 10
  folder: files
  max-width: 1080
  max-height: 566

author:
  banner:
    kafka_topic: "user_ban"
    rejected_posts_to_ban: 5
    scheduler:
      cron: "0 0 3 * * *" #every day at 03.00

user:
  comment:
    kafka_topic: "comment-create"
