spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          likeEvent:faang.school.postservice.dto.kafka.event.like.LikeEvent,
          unlikeEvent:faang.school.postservice.dto.kafka.event.like.UnlikeEvent
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  redis:
    enabled: false

logging:
  level:
    org.testcontainers: INFO
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG