ALTER TABLE post
    ADD COLUMN verification_status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED';

ALTER TABLE post
    ADD COLUMN verified_date TIMESTAMPTZ;

ALTER TABLE post
    ADD COLUMN views BIGINT;