DROP TABLE likes;

CREATE TABLE post_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    post_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_post_likes PRIMARY KEY (id)
);

ALTER TABLE post_likes
    ADD CONSTRAINT FK_POST_LIKES_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

CREATE TABLE comment_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    comment_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment_likes PRIMARY KEY (id)
);

ALTER TABLE comment_likes
    ADD CONSTRAINT FK_COMMENT_LIKES_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);