ALTER TABLE post_resource ALTER COLUMN key TYPE VARCHAR(50);
ALTER TABLE post_resource ALTER COLUMN key SET NOT NULL;
ALTER TABLE post_resource ALTER COLUMN name TYPE VARCHAR(150);
ALTER TABLE post_resource ALTER COLUMN name DROP NOT NULL;
ALTER TABLE post_resource ALTER COLUMN type TYPE VARCHAR(50);
ALTER TABLE post_resource ALTER COLUMN size SET NOT NULL;
ALTER TABLE post_resource DROP COLUMN IF EXISTS status;
ALTER TABLE post_resource DROP COLUMN IF EXISTS updated_at;
ALTER TABLE post_resource ALTER COLUMN post_id SET NOT NULL;