CREATE TABLE IF NOT EXISTS album_users
(
    id       BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    album_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT fk_album_id FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);