name: CI pipeline Kraken

on: [push, pull_request]
 # pull_request:
  #  branches:
   #   - 'kraken-master-stream10'
#  push:
#    branches:
#      - ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v1
      - name: Set up JDK
        uses: action/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run tests with Gradle
        run: ./gradlew.bat test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/build/reports/tests
            **/build/test-results
      
