name: Compile and Test

on:
  pull_request:
    branches:
      - medusa-master
  push:
    branches:
      - medusa-master

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: gradle

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon